### ISSUE TITLE
AppVeyor tests failing

### ISSUE THREAD

**Issue by traversaro** [robotology/ycm#118] opened 2017-06-19 11:07 UTC
The tests are failing with these message:
~~~
5: include_url HASH mismatch
5:    for file: [C:/projects/ycm/build/tests/YCMBootstrap-disable-find/CMakeFiles/CMakeParseArguments.cmake]
5:     expected hash: [8adc20a6a6a0ca5a82338b6edc3cd6e24ba7b3f2]
5:       actual hash: [40ec7d375515c1ad52116d2031b666ea1fa241d9]
5: 
5: Downloading CMakeParseArguments.cmake - Attempt 2 of 3
5: include_url HASH mismatch
5:    for file: [C:/projects/ycm/build/tests/YCMBootstrap-disable-find/CMakeFiles/CMakeParseArguments.cmake]
5:     expected hash: [8adc20a6a6a0ca5a82338b6edc3cd6e24ba7b3f2]
5:       actual hash: [40ec7d375515c1ad52116d2031b666ea1fa241d9]
5: 
5: Downloading CMakeParseArguments.cmake - Attempt 3 of 3
5: CMake Error at C:/projects/ycm/build/tests/YCMBootstrap-disable-find/cmake/IncludeUrl.cmake:348 (message):
5:   include_url HASH mismatch
5: 
5:      for file: [C:/projects/ycm/build/tests/YCMBootstrap-disable-find/CMakeFiles/CMakeParseArguments.cmake]
5:       expected hash: [8adc20a6a6a0ca5a82338b6edc3cd6e24ba7b3f2]
5:         actual hash: [40ec7d375515c1ad52116d2031b666ea1fa241d9]
5: 
5: Call Stack (most recent call first):
~~~
I saw a similar error message also this weekend on a Ubuntu 16.04 system.

**Comment by PeterBowman** [comment] 2017-06-25 20:08
Same [here](https://travis-ci.org/roboticslab-uc3m/openrave-yarp-plugins/jobs/244684288#L6880) for Travis CI on several repos at our org. Apparently, no changes to `CMakeParseArguments.cmake` have been introduced for a long time ([ref](https://github.com/robotology/ycm/commits/master/cmake-next/proposed/CMakeParseArguments.cmake)) and still the expected hash was changed. The offending commit was 4cf8804 (cc @drdanz).

**Comment by traversaro** [comment] 2017-09-16 08:27
I reproduced this issue also by trying to bootstrap a superbuild on WSL .

**Comment by drdanz** [comment] 2017-09-18 09:57
I think there are 3 problems here:
1. CMakeParseArguments.cmake is now a builtin command, but we still support CMake 3.4 so we need a version of the file actually containing the command.
2. We have a "proposed" version of the CMakeParseArguments.cmake that was not accepted upstream. I don't remember if we still need that or not. The problem was the parsing of empty commands.
3. On windows, depending on git configuration, the files are saved with windows EOL.

* `8adc20a6a6a0ca5a82338b6edc3cd6e24ba7b3f2` is the sha1sum for the version in `cmake-next/v3.4.3/CMakeParseArguments.cmake`
* `40ec7d375515c1ad52116d2031b666ea1fa241d9` is the sha1sum for the proposed version (`cmake-next/proposed/CMakeParseArguments.cmake`) converted to windows EOL.

**Comment by PeterBowman** [comment] 2017-12-22 11:15
I couldn't reproduce this on YCM v0.6.0, looks like it's solved. This bug affected v0.2.3 and v0.4.0.

**Comment by drdanz** [comment] 2018-01-09 07:25
Thanks @PeterBowman for testing!
I'll close the issue then.

**Closed by drdanz** 2018-01-09 07:25 UTC
Labels: Platform: Windows
