### ISSUE TITLE
YCM Bootstrap failing on Windows (AppVeyor)

### ISSUE THREAD

**Issue by traversaro** [robotology/ycm#86] opened 2015-10-19 13:36 UTC
At some point ~20 days ago, YCM Bootstrap has started failing on AppVeyor: 
Last "working" (at least for the YCM Bootstrap) build : https://ci.appveyor.com/project/traversaro/codyco-superbuild/build/1.0.204
First "not working" build : https://ci.appveyor.com/project/traversaro/codyco-superbuild/build/1.0.205
Error is:
~~~
-- Downloading ExternalProject.cmake - SUCCESS
CMake Warning (dev) at build/CMakeFiles/ExternalProject.cmake:280 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.
 
  Quoted keywords like "COMMAND" will no longer be interpreted as keywords
  when the policy is set to NEW.  Since the policy is not set the OLD
  behavior will be used.
Call Stack (most recent call first):
  build/CMakeFiles/ExternalProject.cmake:2220 (_ep_parse_arguments)
  build/CMakeFiles/YCMEPHelper.cmake:1008 (ExternalProject_Add)
  build/CMakeFiles/YCMEPHelper.cmake:1252 (ycm_ep_helper)
  cmake/YCMBootstrap.cmake:106 (ycm_bootstrap)
  CMakeLists.txt:69 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.
 
-- Performing download step (git clone) for 'YCM'
-- Performing update step for 'YCM'
-- Performing configure step for 'YCM'
CMake Error at build/CMakeFiles/YCMEPHelper.cmake:1284 (message):
  Cannot configure YCM repository
Call Stack (most recent call first):
  cmake/YCMBootstrap.cmake:106 (ycm_bootstrap)
  CMakeLists.txt:69 (include)
 ~~~

**Comment by drdanz** [comment] 2015-10-19 14:14
The log is not really useful... Can you enable `YCM_BOOTSTRAP_VERBOSE` on appveyor?

**Comment by traversaro** [comment] 2015-10-19 14:17
I will do it (by the way I just noticed that the failure was noticed also by YCM AppVeyor).

**Comment by drdanz** [comment] 2015-10-19 14:26
On YCM AppVeyor the issue is different, it was failing for an broken SSL certificate, then at some point the certificate was fixed, but meanwhile I merged the tests for the IncludeUrl module, that are not executed for some unknown reason.
Right now the SSL certificate should be ok, and the tests are not performed in bootstrap phase, therefore the issue is different.

**Comment by traversaro** [comment] 2015-10-20 10:54
Tried on both `codyco-superbuild` and `iDynTree-superbuild` : 

### `codyco-superbuild`
https://ci.appveyor.com/project/traversaro/codyco-superbuild/build/1.0.222
~~~
-- Downloading file Modules/CMakePackageConfigHelpers.cmake from CMake git repository (ref 52584050c2bb0d65b60b0164af6a28c2761d1598)
CMake Error at cmake-next/CMakeLists.txt:65 (file):
  file DOWNLOAD HASH mismatch
 
    for file: [C:/dev/codyco-superbuild/build/external/YCM/cmake-next/CMakeFiles/cmake-52584050c2bb0d65b60b0164af6a28c2761d1598.dir/downloads/Modules/CMakePackageConfigHelpers.cmake]
      expected hash: [0e368e99c163b56239faf2542fa3ae8a04d38eca]
        actual hash: [da39a3ee5e6b4b0d3255bfef95601890afd80709]
             status: [7;"couldn't connect to server"]
 
Call Stack (most recent call first):
  cmake-next/CMakeLists.txt:159 (_ycm_cmake_next_download_now)
~~~

### `idyntree-superbuild`
https://ci.appveyor.com/project/traversaro/idyntree-superbuild/build/1.0.20
~~~
-- Downloading file Modules/CMakePackageConfigHelpers.cmake from CMake git repository (ref 52584050c2bb0d65b60b0164af6a28c2761d1598)
CMake Error at cmake-next/CMakeLists.txt:65 (file):
  file DOWNLOAD HASH mismatch
 
    for file: [C:/dev/iDynTree-superbuild/build/external/YCM/cmake-next/CMakeFiles/cmake-52584050c2bb0d65b60b0164af6a28c2761d1598.dir/downloads/Modules/CMakePackageConfigHelpers.cmake]
      expected hash: [0e368e99c163b56239faf2542fa3ae8a04d38eca]
        actual hash: [da39a3ee5e6b4b0d3255bfef95601890afd80709]
             status: [51;"SSL peer certificate was not ok"]
 
Call Stack (most recent call first):
  cmake-next/CMakeLists.txt:159 (_ycm_cmake_next_download_now)
~~~

Perhaps it is issue in AppVeyor workers.

**Comment by drdanz** [comment] 2015-10-21 23:15
@traversaro I pushed a few changes to the build system and to the IncludeUrl module. Now instead of failing immediately, it tries to download the file up to 3 times.
I also changed the default download url for CMake modules from CMake gitweb to github, that from my tests seems to be more reliable.

YCM now builds correctly on [AppVeyor](https://ci.appveyor.com/project/drdanz/ycm/build/0.2.0.304), let me know if this helps in your projects as well.

**Comment by traversaro** [comment] 2015-10-26 17:31
Both fail for a error on SSL certificate:
* https://ci.appveyor.com/project/traversaro/codyco-superbuild/build/1.0.231
* https://ci.appveyor.com/project/traversaro/idyntree-superbuild/build/1.0.22 

It is probably some AppVeyor specific problem...

**Comment by drdanz** [comment] 2015-10-28 14:25
Should be fixed now. Please reopen if it is not

**Closed** 2015-10-28 14:25 UTC
